export interface DateSpot {
  id: string;
  name: string;
  area: string;
  vibe: string;
  emoji: string;
  /** coordenadas reais em São Paulo */
  lat: number;
  lng: number;
}

export const DATE_SPOTS: DateSpot[] = [
  {
    id: "ibirapuera",
    name: "Parque Ibirapuera",
    area: "Vila Mariana",
    vibe: "Piquenique, pôr do sol e conversa que não acaba",
    emoji: "🌳",
    lat: -23.5874,
    lng: -46.6576,
  },
  {
    id: "paulista",
    name: "Avenida Paulista",
    area: "Bela Vista",
    vibe: "Andar sem rumo, MASP e um doce no caminho",
    emoji: "🏙️",
    lat: -23.5614,
    lng: -46.6558,
  },
  {
    id: "vila-madalena",
    name: "Beco do Batman",
    area: "Vila Madalena",
    vibe: "Grafite, fotos bobas e café escondido",
    emoji: "🎨",
    lat: -23.554,
    lng: -46.6912,
  },
  {
    id: "liberdade",
    name: "Liberdade",
    area: "Centro",
    vibe: "Lámen, doces japoneses e lanterninhas vermelhas",
    emoji: "🏮",
    lat: -23.5587,
    lng: -46.635,
  },
  {
    id: "arcade",
    name: "Fliperama Retrô",
    area: "Pinheiros",
    vibe: "Modo co-op ativado — sem killer dessa vez",
    emoji: "🕹️",
    lat: -23.5665,
    lng: -46.693,
  },
  {
    id: "cinema",
    name: "Cine + Sorvete",
    area: "Itaim",
    vibe: "Filme de terror e mão gelada pra segurar",
    emoji: "🎬",
    lat: -23.586,
    lng: -46.68,
  },
  {
    id: "aquario",
    name: "Aquário de SP",
    area: "Ipiranga",
    vibe: "Bichinhos fofos e você fazendo 'awnnn'",
    emoji: "🐠",
    lat: -23.5988,
    lng: -46.6088,
  },
  {
    id: "mercadao",
    name: "Mercadão Municipal",
    area: "Centro",
    vibe: "Sanduíche de mortadela dividido no meio",
    emoji: "🥪",
    lat: -23.5417,
    lng: -46.6294,
  },
  {
    id: "mercado-pinheiros",
    name: "Mercado de Pinheiros",
    area: "Pinheiros",
    vibe: "Pastel de bacalhau, caldo de cana e gente feliz",
    emoji: "🥟",
    lat: -23.5665,
    lng: -46.702,
  },
  {
    id: "coco-bambu",
    name: "Coco Bambu Morumbi",
    area: "Morumbi",
    vibe: "Camarão gigante e conta dividida no amor",
    emoji: "🦐",
    lat: -23.623,
    lng: -46.699,
  },
  {
    id: "rua-25",
    name: "Rua 25 de Março",
    area: "Centro",
    vibe: "Caça aos mimos mais fofos e baratos da cidade",
    emoji: "🎀",
    lat: -23.5427,
    lng: -46.6335,
  },
  {
    id: "batata",
    name: "Praça Benedito Calixto",
    area: "Pinheiros",
    vibe: "Feirinha de sábado, antiguidades e chorinho ao vivo",
    emoji: "🎻",
    lat: -23.5588,
    lng: -46.6885,
  },
  {
    id: "bela-vista-cantina",
    name: "Cantinas do Bixiga",
    area: "Bela Vista",
    vibe: "Massa italiana, luz baixa e conversa longa",
    emoji: "🍝",
    lat: -23.5573,
    lng: -46.6437,
  },
  {
    id: "pinacoteca",
    name: "Pinacoteca + Parque da Luz",
    area: "Luz",
    vibe: "Arte, café da manhã tardio e mão dada",
    emoji: "🖼️",
    lat: -23.5343,
    lng: -46.6337,
  },
  {
    id: "farol-santander",
    name: "Farol Santander",
    area: "Centro",
    vibe: "SP inteira lá de cima, só pra gente",
    emoji: "🌆",
    lat: -23.5459,
    lng: -46.6349,
  },
  {
    id: "vila-mada-bar",
    name: "Bares da Vila Madalena",
    area: "Vila Madalena",
    vibe: "Petisco, música alta e você rindo demais",
    emoji: "🍻",
    lat: -23.5556,
    lng: -46.689,
  },
  {
    id: "villa-lobos",
    name: "Parque Villa-Lobos",
    area: "Alto de Pinheiros",
    vibe: "Bike, sorvete e preguiça na grama",
    emoji: "🚲",
    lat: -23.546,
    lng: -46.725,
  },
  {
    id: "zoo",
    name: "Zoológico de SP",
    area: "Água Funda",
    vibe: "Bichinhos e você fazendo carinha de 'quero levar'",
    emoji: "🦩",
    lat: -23.6486,
    lng: -46.6222,
  },
  {
    id: "eataly",
    name: "Eataly São Paulo",
    area: "Jardim Paulista",
    vibe: "Gelato, massa fresca e passeio gostoso",
    emoji: "🍨",
    lat: -23.5952,
    lng: -46.674,
  },
  {
    id: "sesc-pompeia",
    name: "SESC Pompeia",
    area: "Pompeia",
    vibe: "Show, jogo de tabuleiro e comida boa",
    emoji: "🎲",
    lat: -23.5259,
    lng: -46.689,
  },
];
